source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DGSnackbar_Example', :exclusive => true do
  pod "DGSnackbar", :path => "../"
end

target 'DGSnackbar_Tests', :exclusive => true do
  pod "DGSnackbar", :path => "../"

  
end
